variable "location" {}
variable "resource_group_name" {}
variable "vnet_name" {}
variable "address_space" {}
variable "vm_name" {}
variable "vm_size" {}
variable "admin_username" {}
variable "admin_password" {}
variable "storage_account_name" {}